@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.acess_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jonny Doe",
  "documentId": "090.090.090-00",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "documentId": "090.090.090-00",
  "password": "12345678"
}